import { useParams } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { jsPDF } from 'jspdf'
import { toast } from 'react-hot-toast'
import { FiCheckCircle, FiDownload, FiHome } from 'react-icons/fi'
import api from '../../api/client'
import { GlassCard, GlassButton } from '../../components/ui'

export default function ThankYou() {
  const { responseId } = useParams()

  const { data: receipt, isLoading } = useQuery({
    queryKey: ['receipt', responseId],
    queryFn: async () => {
      const { data } = await api.get(`/public/responses/${responseId}`)
      return data.receipt
    },
  })

  const downloadPDF = () => {
    if (!receipt) return

    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()
    let yPos = 20

    // Title
    doc.setFontSize(20)
    doc.setTextColor(102, 126, 234) // Purple
    doc.text('Response Receipt', pageWidth / 2, yPos, { align: 'center' })
    yPos += 15

    // Form title
    doc.setFontSize(14)
    doc.setTextColor(60, 60, 60)
    doc.text(receipt.formTitle, pageWidth / 2, yPos, { align: 'center' })
    yPos += 15

    // Submitted date
    doc.setFontSize(10)
    doc.setTextColor(128, 128, 128)
    doc.text(
      `Submitted: ${new Date(receipt.submittedAt).toLocaleString()}`,
      pageWidth / 2,
      yPos,
      { align: 'center' }
    )
    yPos += 5

    // Response ID
    doc.text(`Response ID: ${receipt.id}`, pageWidth / 2, yPos, {
      align: 'center',
    })
    yPos += 15

    // Divider
    doc.setDrawColor(200, 200, 200)
    doc.line(20, yPos, pageWidth - 20, yPos)
    yPos += 15

    // Answers
    doc.setFontSize(12)
    receipt.answers.forEach((item) => {
      // Check for page break
      if (yPos > 270) {
        doc.addPage()
        yPos = 20
      }

      // Question
      doc.setTextColor(102, 126, 234)
      doc.setFont(undefined, 'bold')
      const questionLines = doc.splitTextToSize(item.question, pageWidth - 40)
      doc.text(questionLines, 20, yPos)
      yPos += questionLines.length * 6 + 2

      // Answer
      doc.setTextColor(60, 60, 60)
      doc.setFont(undefined, 'normal')
      const answerText = item.answer || '-'
      const answerLines = doc.splitTextToSize(String(answerText), pageWidth - 40)
      doc.text(answerLines, 20, yPos)
      yPos += answerLines.length * 6 + 10
    })

    // Footer
    doc.setFontSize(8)
    doc.setTextColor(180, 180, 180)
    doc.text(
      'Generated by Glass Forms',
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    )

    doc.save(`receipt-${receipt.id.slice(0, 8)}.pdf`)
    toast.success('PDF downloaded!')
  }

  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="w-8 h-8 border-4 border-white/20 border-t-purple-400 rounded-full animate-spin" />
      </div>
    )
  }

  return (
    <div className="min-h-screen flex items-center justify-center p-4">
      <GlassCard className="max-w-lg w-full text-center">
        <div className="w-20 h-20 rounded-full bg-green-500/20 flex items-center justify-center mx-auto mb-6">
          <FiCheckCircle className="w-10 h-10 text-green-400" />
        </div>

        <h1 className="text-3xl font-bold text-white mb-2">Thank You!</h1>
        <p className="text-white/60 mb-6">
          Your response has been submitted successfully.
        </p>

        {receipt && (
          <div className="bg-white/5 rounded-xl p-4 mb-6 text-left">
            <h2 className="text-white font-medium mb-3">{receipt.formTitle}</h2>
            <div className="space-y-2 text-sm">
              <div className="flex justify-between">
                <span className="text-white/50">Response ID</span>
                <span className="text-white font-mono text-xs">
                  {receipt.id.slice(0, 8)}...
                </span>
              </div>
              <div className="flex justify-between">
                <span className="text-white/50">Submitted</span>
                <span className="text-white">
                  {new Date(receipt.submittedAt).toLocaleString()}
                </span>
              </div>
            </div>
          </div>
        )}

        <div className="flex gap-3 justify-center">
          <GlassButton onClick={() => (window.location.href = '/')}>
            <FiHome className="w-4 h-4" />
            Home
          </GlassButton>
          <GlassButton variant="primary" onClick={downloadPDF}>
            <FiDownload className="w-4 h-4" />
            Download Receipt
          </GlassButton>
        </div>
      </GlassCard>
    </div>
  )
}
